sudo: false
language: go
go:
  - 1.11.x
install:
  - nvm install 9.11
  - npm install -g source-map-support
  - go get -u github.com/gopherjs/gopherjs
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.12.5
  - go get -u github.com/haya14busa/goverage
  - npm install --global node-gyp
before_script:
  - export NODE_PATH="/usr/local/lib/node_modules"

  # Set up system calls for gopherjs test (nodejs).
  # https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md
  - cd $GOPATH/src/github.com/gopherjs/gopherjs/node-syscall/
  - node-gyp rebuild
  - mkdir -p ~/.node_libraries/
  - cp build/Release/syscall.node ~/.node_libraries/syscall.node
  - cd $TRAVIS_BUILD_DIR
script:
  # Fetch dependencies.
  - go get -t -v ./...
  - GO111MODULE=on go get -v ./...

  # Consult Go fmt to ensure consistent code style.
  - diff -u <(echo -n) <(gofmt -d -s .)

  # Consult golangci-lint (multiple Go linting tools).
  - golangci-lint run . ./elem/... ./event/... ./example/...
  - golangci-lint run --exclude 'exported .* should have comment .*or be unexported' ./prop/... ./style/... # https://github.com/gopherjs/vecty/issues/227
  - GOOS=js GOARCH=wasm golangci-lint run --build-tags 'js wasm' . ./elem/... ./event/... ./example/...
  - GOOS=js GOARCH=wasm golangci-lint run --build-tags 'js wasm' --exclude 'exported .* should have comment .*or be unexported' ./prop/... ./style/... # https://github.com/gopherjs/vecty/issues/227

  # Test with Go compiler and GopherJS compiler.
  - go test -v -race ./...
  - gopherjs test -v ./...

  # Generate and upload coverage to codecov.io
  - goverage -covermode=atomic -coverprofile=coverage.out $(go list ./... | grep -v -e vecty/elem -e vecty/event -e vecty/example -e vecty/prop -e vecty/style)
  - include_cov=coverage.out bash <(curl -s https://codecov.io/bash)
